In [36]:
import numpy as np 
import math as math

In [ ]:
# Insertion-sort
size = 4
x = np.zeros(size)

In [ ]:
# Create the array
x[0] = 45
x[1] = 10
x[2] = 100
x[3] = 5

In [ ]:
for j in range(1,size):
  key = x[j]
  i = j-1
  while (i >= 0 and x[i] > key):
    x[i+1] = x[i]
    i = i-1
  x[i+1] = key
x

array([  5.,  10.,  45., 100.])

In [ ]:
for j in range(1,size):
  key = x[j]
  i = j-1
  while (i >= 0 and x[i] < key):
    x[i+1] = x[i]
    i = i-1
  x[i+1] = key
x

array([100.,  45.,  10.,   5.])

In [ ]:
size = 4
x = np.array([1,2,3,4])
Va = 10

for i in range(size):
  if x[i] == Va:
    print(i)
  elif (i+1) == size:
    print("No existe dicho valor")
  else: 
    continue


No existe dicho valor


#MERGE-SORT

In [44]:
import math

def merge(items, p, q, r):
    L = items[p:q+1]        #  Toma desde p hasta q
    R = items[q+1:r+1]      #  toma desde q+1 hasta r
    i = j = 0
    k = p
    while i < len(L) and j < len(R):
        if(L[i] < R[j]):
            items[k] = L[i]
            i += 1
        else:
            items[k] = R[j]
            j += 1
        k += 1
    if(j == len(R)):
        items[k:r+1] = L[i:]



def mergesort(items, p, r):
    if(p < r):
        q = math.floor((p+r)/2)
        print(items)
        mergesort(items, p, q)
        print(items)
        mergesort(items, q+1, r)
        print(items)
        merge(items, p, q, r)


items = [4,3,2,1,17]
mergesort(items, 0, len(items)-1)
items

[4, 3, 2, 1, 17]
[4, 3, 2, 1, 17]
[4, 3, 2, 1, 17]
[4, 3, 2, 1, 17]
[4, 3, 2, 1, 17]
[3, 4, 2, 1, 17]
[3, 4, 2, 1, 17]
[2, 3, 4, 1, 17]
[2, 3, 4, 1, 17]
[2, 3, 4, 1, 17]
[2, 3, 4, 1, 17]
[2, 3, 4, 1, 17]


[1, 2, 3, 4, 17]

In [47]:
def mergesort(items, p, r):
    if(p < r):
        q = math.floor((p+r)/2)
        print(q)
        print(items)
        mergesort(items, p, q)
        mergesort(items, q+1, r)
        print(items)
        merge(items, p, q, r)
        print(items)

items = [4,3,2,1,17]
mergesort(items, 0, len(items)-1)
items

2
[4, 3, 2, 1, 17]
1
[4, 3, 2, 1, 17]
0
[4, 3, 2, 1, 17]
[4, 3, 2, 1, 17]
[3, 4, 2, 1, 17]
[3, 4, 2, 1, 17]
[2, 3, 4, 1, 17]
3
[2, 3, 4, 1, 17]
[2, 3, 4, 1, 17]
[2, 3, 4, 1, 17]
[2, 3, 4, 1, 17]
[1, 2, 3, 4, 17]


[1, 2, 3, 4, 17]

In [ ]:
def tri_recursion(k):
  if(k>0):
    result = k+tri_recursion(k-1)
    print(result)
  else:0
    result = 0
  return result

print("\n\nRecursion Example Results")
tri_recursion(6)



Recursion Example Results
1
3
6
10
15
21


21

https://github.com/gzc/CLRS/blob/master/C02-Getting-Started/exercise_code/merge-sort.py


https://github.com/deniederhut/intro-to-algorithms

In [37]:
def MERGE(A,p,q,r):
  n1 = q - p + 1    #   Elementos en A, desde p hasta q
  n2 = r - q        #   Elementos en A, desde q+1, hasta R
  L = np.zeros(n1+1) #  n1 + 1 elementos
  R = np.zeros(n2+1) #  n2 + 1 elementos
  for i in range(n1):
    L[i] = A[p + i]
  for j in range(n2):
    R[j] = A[q + j + 1]  
  i = 0
  j = 0
  for k in range(p,r+1):
    if L[i] <= R[j]:
      A[k] = L[i]
      i =+ 1
    else: 
      A[k] = R[j]
      j =+ 1

In [42]:
def MERGE_SORT(A,p,r):
  if p < r:
    q = math.floor((p+r)/2)
    print(A)
    MERGE_SORT(A,p,q) 
    print(A)
    MERGE_SORT(A,q+1,r)
    MERGE(A,p,q,r)


In [43]:

A = [4,3,2,1]
MERGE_SORT(A, 0, len(A)-1)
A

[4, 3, 2, 1]
[4, 3, 2, 1]
[4, 3, 2, 1]
[3.0, 0.0, 2, 1]
[3.0, 0.0, 2, 1]
[3.0, 0.0, 2, 1]


[1.0, 0.0, 0.0, 0.0]

In [33]:
np.zeros(2)

array([0., 0.])